#! /usr/bin/env python3
from CGen import CGen
from CGenOptionsDB import OptionsInitialize

def main():
    opts = OptionsInitialize()
    with CGen(opts) as cgen:
        cgen.Setup()
        cgen.PartitionMesh()
        cgen.GenerateElements()

if __name__ == "__main__":
    main()