#! /usr/bin/env python3
import pyhesive

def main():
    with pyhesive.Mesh() as msh:
        msh.PartitionMesh()
        msh.GenerateElements()
        msh.WriteMesh()

if __name__ == "__main__":
    main()
